# Generated by Django 5.1.2 on 2024-10-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0006_rename_last_updated_match_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chess_app.match'),
        ),
    ]
